(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
Print["Mathematica was called from directory ",Directory[]]

(* Choice of outputfile *)
ResultsDirectory = Directory[];
$Outputfile = ResultsDirectory<>"/Yi_Final.csv";

$PRIMATPATH="../";(*To me modified if it is elsewhere*)

(*Print["Current directory is ,"Directory[]]*)


(* ::Input::Initialization:: *)
If[Length[$CommandLine]>=4,
ExtraArguments=Drop[$CommandLine,3];
Print["Extra arguments are ",ExtraArguments]
]



(* ::Input::Initialization:: *)

Off[General::munfl];
(*Print["I will now call PRIMAT-Main.m \n"];*)
AbsoluteTiming[Get[$PRIMATPATH<>"PRIMAT-Main.m"]];

ToExpression/@ExtraArguments

(*Print["$ReducedNetwork ",$ReducedNetwork]
Print["Meanh2\[CapitalOmega]b0 ",Meanh2\[CapitalOmega]b0]*)


(* ::Input::Initialization:: *)
(*Print["$ReducedNetwork = ",$ReducedNetwork];*)


(* ::Input::Initialization:: *)
timing=AbsoluteTiming[Block[{Print},
RunNumericalIntegrals;
]]
Print["I have finished with the BBN network in ",timing[[1]]," s. and I will output in file : ",$Outputfile];


(* ::Input::Initialization:: *)
AllResults={#,Yf[#]}&/@ShortNames;
ImportResults={{"Neff",Neff},{"YP",4Yf["a"]},{"D/H",YfH["d"]},{"He3/H",YfH["t"]+YfH["He3"]},{"Li7/H",YfH["Li7"]+YfH["Be7"]}};

TableResults =Join[ImportResults,AllResults]

Print["Results are ",TableResults]

Export[$Outputfile,TableResults,"CSV"];


(* ::Input::Initialization:: *)
Exit[];
