(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(* Choice of outputfile *)
ResultsDirectory = Directory[];
$Outputfile = ResultsDirectory<>"/Yi_MC.csv";

$PRIMATPATH="../";(*To me modified if it is elsewhere*)


(* ::Input::Initialization:: *)
If[Length[$CommandLine]>=4,
ExtraArguments=Drop[$CommandLine,3]
]
(*Print["Extra arguments are ",ExtraArguments]*)



(* ::Input::Initialization:: *)
Print["For info the outputfile is ",$Outputfile]


(* ::Input::Initialization:: *)
LengthMC=10;(* Should be 1000 to get precise estimation of errors due to nuclear rates *)


(* ::Input::Initialization:: *)
Off[General::munfl];
AbsoluteTiming[Get[$PRIMATPATH<>"PRIMAT-Main.m"]]

ToExpression/@ExtraArguments


(* ::Input::Initialization:: *)
(*Print["$ReducedNetwork = ",$ReducedNetwork];*)
Print["Eta is ",Eta];
Print["LengthMC is ",LengthMC]


(* ::Input::Initialization:: *)
$ParallelBool=True;
$RandomNuclearRates=True;
$Random\[Tau]neutron=True;
$Randomh2\[CapitalOmega]b=False;(*No Monte Carlo on baryons becauseuncertainty is computed for a given baryon bundance.*)
(*LoadRatesFull;*)


(* ::Input::Initialization:: *)
Print["\[CapitalOmega]bh2Over\[Eta] ",\[CapitalOmega]bh2Over\[Eta]]


(* ::Input::Initialization:: *)
ComputePrincipalAbundanceBaryons[eta_]:=Module[{Meanh2\[CapitalOmega]b0Old},
Meanh2\[CapitalOmega]b0=\[CapitalOmega]bh2Over\[Eta] eta;

RunPRIMATMonteCarlo[LengthMC];

YP=4ElementColumn["a"];
YDH=ElementColumn["d"]/ElementColumn["p"];
YHe3H=(ElementColumn["t"]+ElementColumn["He3"])/ElementColumn["p"];
YLi7H=(ElementColumn["Li7"]+ElementColumn["Be7"])/ElementColumn["p"];


{YP,YDH,YHe3H,YLi7H}

]


(* ::Input::Initialization:: *)
results=ComputePrincipalAbundanceBaryons[Eta];
Print["Table of results ",results];
Export[$Outputfile,results,"CSV"];



(* ::Input::Initialization:: *)
Exit[]
